services:
  postgres:
    image: postgres:16.1
    volumes:
      - pg-data-hvc:/var/lib/postgresql_16/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  pg-data-hvc:
    driver: local
